# Generated by Django 6.0.3 on 2026-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('Worship', 'Worship'), ('Conference', 'Conference'), ('Youth', 'Youth'), ('Outreach', 'Outreach'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
